# Generated by Django 4.1.4 on 2022-12-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.JSONField()),
                ('team_to_play', models.IntegerField(choices=[(1, 'White'), (2, 'Black')])),
                ('game_ended', models.BooleanField(default=False)),
            ],
        ),
    ]
