# Generated by Django 4.1.4 on 2022-12-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_alter_game_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='table',
            new_name='table_data',
        ),
    ]
