# Generated by Django 4.1.4 on 2022-12-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_rename_table_game_table_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_to_play',
            field=models.IntegerField(choices=[(1, 'White'), (2, 'Black')], default=1),
        ),
    ]
